### ISSUE TITLE
generic dependencies

### ISSUE THREAD

**Issue by Sobes76rus** [taskiq-python/taskiq#122]
Looks like generic class as dependency could not resolve inner dependencies

```python
import asyncio
from concurrent.futures import ThreadPoolExecutor
from typing import Generic, TypeVar

from taskiq import InMemoryBroker, TaskiqDepends, TaskiqMessage
from taskiq.receiver import Receiver

_T = TypeVar("_T")


broker = InMemoryBroker()


async def db_connection() -> str:
    return "let's pretend as this is a connection"


class MyDAO(Generic[_T]):
    def __init__(self, db_conn: str = TaskiqDepends(db_connection)):
        self.db_conn = db_conn

    def get_users(self) -> str:
        return self.db_conn


@broker.task
def my_task(dao: MyDAO = TaskiqDepends()) -> None:
    return dao.get_users()


async def run():
    receiver = Receiver(
        broker,
        executor=ThreadPoolExecutor(max_workers=10),
        validate_params=True,
        max_async_tasks=-1,
    )

    result = await receiver.run_task(
        my_task,
        TaskiqMessage(
            task_id="task_id",
            task_name=my_task.task_name,
            labels={},
            args=[],
            kwargs={},
        ),
    )

    assert result.return_value == await db_connection(), result.return_value


asyncio.run(run())

```

```
Traceback (most recent call last):
  File "test.py", line 53, in <module>
    asyncio.run(run())
  File "/home/artverum/miniconda3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/home/artverum/miniconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "test.py", line 50, in run
    assert result.return_value == await db_connection(), result.return_value
AssertionError: <taskiq_dependencies.dependency.Dependency object at 0x7f1f775ce1c0>

```

**Comment by s3rius** [comment]
Good evening. I've seen you request, but I decided to play around with generics and make them resolvable. Now you can depend on TypeVar types. 

The PR: https://github.com/taskiq-python/taskiq-dependencies/pull/12.
