### ISSUE TITLE
Issue Conflicting subparser 

### ISSUE THREAD

**Issue by Markushik** [taskiq-python/taskiq#180]
**Operating System: Windows 11
Python: 3.11.4
poetry: 1.5.1
taskiq: 0.8.4
taskiq-nats: 0.3.0**

**Hello 👋**
Decided to upgrade taskiq `0.8.2` ~> `0.8.4`, when I try to run the script broker or scheduler, I get an error:

```
❯ taskiq worker tasks:broker                                     
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Zemik\AppData\Local\pypoetry\Cache\virtualenvs\controller-new-xTr7bc85-py3.11\Scripts\taskiq.exe\__main__.py", line 7, in <module>
  File "C:\Users\Zemik\AppData\Local\pypoetry\Cache\virtualenvs\controller-new-xTr7bc85-py3.11\Lib\site-packages\taskiq\__main__.py", line 54, in main
    subparsers.add_parser(
  File "C:\Users\Zemik\AppData\Local\Programs\Python\Python311\Lib\argparse.py", line 1192, in add_parser
    raise ArgumentError(self, _('conflicting subparser: %s') % name)
argparse.ArgumentError: argument : conflicting subparser: scheduler
```
or

```
❯ taskiq scheduler tasks:scheduler
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Zemik\AppData\Local\pypoetry\Cache\virtualenvs\controller-new-xTr7bc85-py3.11\Scripts\taskiq.exe\__main__.py", line 7, in <module>
  File "C:\Users\Zemik\AppData\Local\pypoetry\Cache\virtualenvs\controller-new-xTr7bc85-py3.11\Lib\site-packages\taskiq\__main__.py", line 54, in main
    subparsers.add_parser(
  File "C:\Users\Zemik\AppData\Local\Programs\Python\Python311\Lib\argparse.py", line 1192, in add_parser
    raise ArgumentError(self, _('conflicting subparser: %s') % name)
argparse.ArgumentError: argument : conflicting subparser: scheduler
```

My code: https://gist.github.com/Markushik/768b0887b92ef420b29e068680c23387
if you need more information, please notify me.
Tnx 🙏

**Comment by vvanglro** [comment]
New behavior of python3.11 https://github.com/python/cpython/issues/94331#issuecomment-1268029720

**Comment by s3rius** [comment]
I cannot as well on python `3.11.4`. I guess there are multiple version of taskiq or entrypoints.
