### ISSUE TITLE
AssertionError after upgrading anyio to 4.7.0

### ISSUE THREAD

**Issue by llybin** [taskiq-python/taskiq#387]
AssertionError after upgrading anyio to 4.7.0

```python
 Traceback (most recent call last):                                                                                                                                                                             │
│   File "/usr/local/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap                                                                                                                         │
│     self.run()                                                                                                                                                                                                 │
│   File "/usr/local/lib/python3.12/multiprocessing/process.py", line 108, in run                                                                                                                                │
│     self._target(*self._args, **self._kwargs)                                                                                                                                                                  │
│   File "/usr/local/lib/python3.12/site-packages/taskiq/cli/worker/run.py", line 153, in start_listen                                                                                                           │
│     loop.run_until_complete(receiver.listen(shutdown_event))                                                                                                                                                   │
│   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete                                                                                                                     │
│     return future.result()                                                                                                                                                                                     │
│            ^^^^^^^^^^^^^^^                                                                                                                                                                                     │
│   File "/usr/local/lib/python3.12/site-packages/taskiq/receiver/receiver.py", line 336, in listen                                                                                                              │
│     async with anyio.create_task_group() as gr:                                                                                                                                                                │
│                ^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                       │
│   File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 772, in __aenter__                                                                                                          │
│     self.cancel_scope.__enter__()                                                                                                                                                                              │
│   File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 425, in __enter__                                                                                                           │
│     task_state = _task_states[host_task]                                                                                                                                                                       │
│                  ~~~~~~~~~~~~^^^^^^^^^^^                                                                                                                                                                       │
│   File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 686, in __getitem__                                                                                                         │
│     assert isinstance(key, asyncio.Task)                                                                                                                                                                       │
│            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                       │
│ AssertionError    
```

https://github.com/agronholm/anyio/releases

Locking anyio=4.6.2 is solved the issue.

**Comment by s3rius** [comment]
Could you please provide more details? I was able to upgrade to `anyio` 4.7.0 without any issues. Is the problem only affects a particular task, or any task? What broker are you using? It would also be very helpful if you could share a minimal reproducible example.

**Comment by llybin** [comment]
@s3rius thank you for the answer.

https://github.com/llybin/taskiq-anyio-4.7.0

`(main) $ docker-compose up ppp-taskiq`

here it reproducing, seems as taskiq configured some weird way in this project, but it worked with anyio=4.6.2

![image](https://github.com/user-attachments/assets/b2c4e854-6071-47b5-8bd7-2c356a99a39f)

**Comment by s3rius** [comment]
@llybin, as a result of my investigation it's not an issue of taskiq. It's `nest_asyncio` which breaks anyio. I have linked the issue where I posted a bit smaller MRE. Please follow up on the related issue instead. 

Thanks you for providing the code.

**Comment by s3rius** [comment]
Also, a small thing to add. I would generally recommend you to avoid using `nest_asyncio`, because of two things: 

* It breaks some assumptions of asyncio
* It was deprecated and repository was archived: https://github.com/erdewit/nest_asyncio

**Comment by llybin** [comment]
Thank you for your help. I will study and take your recommendations into account. All the best.
