### ISSUE TITLE
taskiq auto discover tasks not working

### ISSUE THREAD

**Issue by Kokoserver** [taskiq-python/taskiq#75]
when i run: taskiq worker src.taskiq_tasks.broker:broker --reload --do-not-use-gitignore -fsd

i got this on the log
Cannot import src\taskiq_tasks\auth\tasks
Cannot import src\taskiq_tasks\example\tasks
Cannot import src\taskiq_tasks\staff\tasks
Cannot import src\taskiq_tasks\user\tasks

and when i try to send task i got
"src.taskiq_tasks.user.tasks:send_activation_email" is not found. Maybe you forgot to import it?

**Comment by s3rius** [comment]
Hi, and thanks for raising this issue. Did it work on previous versions? 

What command do you use to run taskiq?

**Comment by Kokoserver** [comment]
well i have just started migrating my app today, let me give that a try

**Comment by Kokoserver** [comment]
i use this exact vertion: taskiq==0.0.8

**Comment by s3rius** [comment]
Current version is 0.3.1. Consider upgrading and try it again.

**Comment by s3rius** [comment]
I've created a PR that may give more info about what's happening.

**Comment by s3rius** [comment]
Consider upgrading to 0.3.2 and try again. Now you could have more information about import errors.

**Comment by Kokoserver** [comment]
seems version  0.3.2 not available yet, trying to install it with poetry, but not found

**Comment by s3rius** [comment]
I guess poetry uses cached version. Try this command:

```bash
poetry update --no-cache
```

**Comment by Kokoserver** [comment]
thanks i was able to upgrade it, now i'm getting the traceback below:

Traceback (most recent call last):
  File "C:\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\owoni\AppData\Local\pypoetry\Cache\virtualenvs\src-jBCvkqrF-py3.11\Lib\site-packages\watchdog\observers\api.py", line 202, in run
    self.dispatch_events(self.event_queue)
  File "C:\Users\owoni\AppData\Local\pypoetry\Cache\virtualenvs\src-jBCvkqrF-py3.11\Lib\site-packages\watchdog\observers\api.py", line 378, in dispatch_events   
    handler.dispatch(event)
  File "C:\Users\owoni\AppData\Local\pypoetry\Cache\virtualenvs\src-jBCvkqrF-py3.11\Lib\site-packages\taskiq\cli\watcher.py", line 42, in dispatch
    if self.gitignore and self.gitignore(event.src_path):
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\owoni\AppData\Local\pypoetry\Cache\virtualenvs\src-jBCvkqrF-py3.11\Lib\site-packages\gitignore_parser.py", line 33, in <lambda>
    return lambda file_path: any(r.match(file_path) for r in rules)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\owoni\AppData\Local\pypoetry\Cache\virtualenvs\src-jBCvkqrF-py3.11\Lib\site-packages\gitignore_parser.py", line 33, in <genexpr>
    return lambda file_path: any(r.match(file_path) for r in rules)
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\owoni\AppData\Local\pypoetry\Cache\virtualenvs\src-jBCvkqrF-py3.11\Lib\site-packages\gitignore_parser.py", line 139, in match
    rel_path = str(Path(abs_path).resolve().relative_to(self.base_path))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\pathlib.py", line 730, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: '\\\\?\\C:\\Users\\owoni\\Documents\\code\\fermerce\\user\\src\\taskiq_tasks\\__pycache__\\broker.cpython-311.pyc.1365321427408' is not in the subpath of 'C:\\Users\\owoni\\Documents\\code\\fermerce\\user' OR one path is relative and the other is absolute.
Cannot import src\taskiq_tasks\auth\tasks. Cause:
No module named 'src\\taskiq_tasks\\auth\\tasks'
Traceback (most recent call last):
  File "C:\Users\owoni\AppData\Local\pypoetry\Cache\virtualenvs\src-jBCvkqrF-py3.11\Lib\site-packages\taskiq\cli\utils.py", line 64, in import_from_modules      
    import_module(module)
  File "C:\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'src\\taskiq_tasks\\auth\\tasks'
Cannot import src\taskiq_tasks\example\tasks. Cause:
No module named 'src\\taskiq_tasks\\example\\tasks'
Traceback (most recent call last):
  File "C:\Users\owoni\AppData\Local\pypoetry\Cache\virtualenvs\src-jBCvkqrF-py3.11\Lib\site-packages\taskiq\cli\utils.py", line 64, in import_from_modules      
    import_module(module)
  File "C:\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'src\\taskiq_tasks\\example\\tasks'
Cannot import src\taskiq_tasks\staff\tasks. Cause:
No module named 'src\\taskiq_tasks\\staff\\tasks'
Traceback (most recent call last):
  File "C:\Users\owoni\AppData\Local\pypoetry\Cache\virtualenvs\src-jBCvkqrF-py3.11\Lib\site-packages\taskiq\cli\utils.py", line 64, in import_from_modules      
    import_module(module)
  File "C:\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'src\\taskiq_tasks\\staff\\tasks'
Cannot import src\taskiq_tasks\user\tasks. Cause:
No module named 'src\\taskiq_tasks\\user\\tasks'
Traceback (most recent call last):
  File "C:\Users\owoni\AppData\Local\pypoetry\Cache\virtualenvs\src-jBCvkqrF-py3.11\Lib\site-packages\taskiq\cli\utils.py", line 64, in import_from_modules      
    import_module(module)
  File "C:\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'src\\taskiq_tasks\\user\\tasks'

**Comment by Kokoserver** [comment]
sorry for the long message, i hope it helps

**Comment by s3rius** [comment]
Sure. Thank you.

**Comment by s3rius** [comment]
I guess, I understood the problem. Will try to fix it.

**Comment by Kokoserver** [comment]
I really appriciate your fast response, Thank you for making this amazing tools

**Comment by s3rius** [comment]
Can you please check if the problem is fixed by using this version in your pyproject.toml?

```toml
taskiq = { branch = "bugfix/windows-path", git = "https://github.com/taskiq-python/taskiq.git" }
```

**Comment by Kokoserver** [comment]
okay am on it

**Comment by Kokoserver** [comment]
please i'm kind of finding it somehow to install with poetry can you help

**Comment by s3rius** [comment]
Replace your taskiq entry with the one I sent you below. And run `poetry update` command.

**Comment by Kokoserver** [comment]
okay, i tried that the error is not comming up, i got this new one:

Traceback (most recent call last):
  File "C:\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\owoni\AppData\Local\pypoetry\Cache\virtualenvs\src-jBCvkqrF-py3.11\Lib\site-packages\watchdog\observers\api.py", line 202, in run
    self.dispatch_events(self.event_queue)
  File "C:\Users\owoni\AppData\Local\pypoetry\Cache\virtualenvs\src-jBCvkqrF-py3.11\Lib\site-packages\watchdog\observers\api.py", line 378, in dispatch_events
    handler.dispatch(event)
  File "C:\Users\owoni\AppData\Local\pypoetry\Cache\virtualenvs\src-jBCvkqrF-py3.11\Lib\site-packages\taskiq\cli\watcher.py", line 42, in dispatch
    if self.gitignore and self.gitignore(event.src_path):
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\owoni\AppData\Local\pypoetry\Cache\virtualenvs\src-jBCvkqrF-py3.11\Lib\site-packages\gitignore_parser.py", line 33, in <lambda>
    return lambda file_path: any(r.match(file_path) for r in rules)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\owoni\AppData\Local\pypoetry\Cache\virtualenvs\src-jBCvkqrF-py3.11\Lib\site-packages\gitignore_parser.py", line 33, in <genexpr>
    return lambda file_path: any(r.match(file_path) for r in rules)
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\owoni\AppData\Local\pypoetry\Cache\virtualenvs\src-jBCvkqrF-py3.11\Lib\site-packages\gitignore_parser.py", line 139, in match
    rel_path = str(Path(abs_path).resolve().relative_to(self.base_path))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\pathlib.py", line 730, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: '\\\\?\\C:\\Users\\owoni\\Documents\\code\\fermerce\\user\\src\\taskiq_tasks\\example\\__pycache__\\tasks.cpython-311.pyc.2554103045040' is not in the subpath of 'C:\\Users\\owoni\\Documents\\code\\fermerce\\user' OR one path is relative and the other is absolute.

**Comment by Kokoserver** [comment]
i try to restart IDE it work thanks to much

**Comment by s3rius** [comment]
Ah, I see. Will release version with this fix soon. 

If your issue is resolved, please close it. Don't forget to hit the star button.

**Comment by s3rius** [comment]
Also, I'll take a look on this problem. It seems like .gitignore matcher has some problems running on windows machines.

**Comment by Kokoserver** [comment]
have just done that, little bit faster than your response 😂😂

**Comment by Kokoserver** [comment]
lastly i should ask this is not related to the error, currently i'm using a kombu to send event to different broker do you think that will work directly using taskiq i thing it has the ability to dispatch message😉

**Comment by s3rius** [comment]
I guess you're talking about celery, right? 

Kombu is a nice library, but it's fully sync. If you want to use taskiq with existing RabbitMQ, you can try using AioPikaBroker from the [taskiq-aio-pika](https://pypi.org/project/taskiq-aio-pika/) package. 

Also celery uses slightly different format than taskiq. You can replace `broker.formatter` with custom formatter. We don't have a built-in celery-like formatter, but it's easy to write your own.

**Comment by Kokoserver** [comment]
okay, thanks i'm closing this issue
